# Generated by Django 2.1.3 on 2018-11-03 13:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('celular', models.TextField(max_length=11, unique=True)),
                ('ra', models.TextField(max_length=7, unique=True)),
                ('foto', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=30)),
                ('descricao', models.TextField(max_length=100, null=True, unique=True)),
                ('conteudo', models.TextField(max_length=8000)),
                ('tipo', models.TextField(max_length=15)),
                ('extras', models.TextField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeVinculada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotulo', models.TextField(max_length=500, unique=True)),
                ('status', models.TextField(max_length=15)),
                ('dtiniresposta', models.DateTimeField(auto_now_add=True)),
                ('dtfimresposta', models.DateTimeField(auto_now_add=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Atividade')),
            ],
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('celular', models.TextField(max_length=11, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.TextField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=30, unique=True)),
                ('data', models.DateField(default=datetime.date.today)),
                ('status', models.TextField(choices=[('ABERTA', 'ABERTA'), ('FECHADA', 'FECHADA')], default='ABERTA', max_length=10)),
                ('plano_ensino', models.TextField(max_length=1000)),
                ('carga_horaria', models.SmallIntegerField()),
                ('competencias', models.TextField(max_length=1000)),
                ('habilidades', models.TextField(max_length=1000)),
                ('ementa', models.TextField(max_length=1000)),
                ('conteudo_programatico', models.TextField(max_length=1000)),
                ('bibliografia_basica', models.TextField(max_length=1000)),
                ('bibliografia_complementar', models.TextField(max_length=1000)),
                ('percentual_pratico', models.SmallIntegerField()),
                ('percentual_teorico', models.SmallIntegerField()),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Coordenador')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaOfertada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtiniciomatricula', models.DateTimeField(auto_now_add=True, null=True)),
                ('dtfimmatricula', models.DateTimeField(auto_now_add=True, null=True)),
                ('ano', models.SmallIntegerField()),
                ('semestre', models.SmallIntegerField()),
                ('turma', models.TextField(max_length=1)),
                ('metodologia', models.TextField(max_length=1000, null=True)),
                ('recursos', models.TextField(max_length=1000, null=True)),
                ('criterioavaliacao', models.TextField(max_length=1000, null=True)),
                ('planosdeaulas', models.TextField(max_length=1000, null=True)),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Coordenador')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Curso')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=100)),
                ('resposta', models.TextField(max_length=8000)),
                ('dtentrega', models.DateTimeField(auto_now_add=True)),
                ('dtavaliacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.TextField(max_length=10)),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('obs', models.TextField(max_length=500, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Aluno')),
                ('atividade_vinculada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.AtividadeVinculada')),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.TextField(max_length=100)),
                ('referencia', models.TextField(max_length=100)),
                ('conteudo', models.TextField(max_length=500)),
                ('status', models.TextField(max_length=50)),
                ('dtenvio', models.DateTimeField(auto_now_add=True)),
                ('dtresposta', models.DateTimeField(auto_now_add=True, null=True)),
                ('resposta', models.TextField(max_length=500, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('celular', models.TextField(max_length=11, unique=True)),
                ('apelido', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoMatricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtresposta', models.DateTimeField(auto_now_add=True)),
                ('status', models.TextField(max_length=15)),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Coordenador')),
                ('disciplinaofertada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.DisciplinaOfertada')),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_expiracao', models.DateField(default=datetime.date(1900, 1, 1))),
                ('login', models.TextField(max_length=30, unique=True)),
                ('senha', models.TextField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='professor',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Usuario'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Professor'),
        ),
        migrations.AddField(
            model_name='entrega',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Professor'),
        ),
        migrations.AddField(
            model_name='disciplinaofertada',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Professor'),
        ),
        migrations.AddField(
            model_name='coordenador',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Usuario'),
        ),
        migrations.AddField(
            model_name='atividadevinculada',
            name='dofertada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.DisciplinaOfertada'),
        ),
        migrations.AddField(
            model_name='atividadevinculada',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Professor'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Professor'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='disciplinaofertada',
            unique_together={('curso', 'disciplina', 'turma', 'ano', 'semestre')},
        ),
    ]
